language: android
jdk: oraclejdk8
android:
    components:
    - tools
    - build-tools-29.0.2
    - android-29
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
script:
    - ./gradlew build
