language: android
jdk: oraclejdk8
android:
    components:
    - tools
    - build-tools-28.0.3
    - android-28
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
script:
    - ./gradlew build
