version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-29
      #- image: circleci/openjdk:8-jdk
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: "dumb"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          keys:
            - v1-gradle-caches-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run: ./gradlew build
      - save_cache:
          key: v1-gradle-caches-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - ~/.gradle/caches/
      - save_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/wrapper/
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports/
